### ISSUE TITLE
Type guessing of 32bit numpy arrays

### ISSUE THREAD

**Issue by HaHeho** [attwad/python-osc#102]
The handling of 64 bit numpy values and arrays works just fine. I have been working with single precision calculations recently and encountered that the message builder fails on that.
```python
from pythonosc.osc_message_builder import OscMessageBuilder
builder = OscMessageBuilder(address='/whatever')
builder.add_arg(np.float32(1.23))
```

This is of course, since `isinstance(np.float32(1.23, 22), float) == False`.  Something similar will happen for other varieties of numpy integers, e.g. `isinstance(np.int16(1), int) == False`. Also complex values would not work, but I think that is out of the scope to send via OSC. Varieties of integers and floats are on the other hand I would say.

Is there an interest on making the behavior more convenient? Otherwise what would be the recommended syntax to safely send array contents like `a = np.array([1, 1], dtype='float32')`. Maybe `osc_client.send_message('/whatever', a.astype('float64'))`, which seems inconvenient? (I have noticed that my other idea of `osc_client.send_message('/whatever', list(a))` does not work since the individual values remain numpy dtypes and hence incompatible to Python float)

**Comment by attwad** [comment]
I haven't played with numpy for years sorry I am not sure how to best support that although I see the need for at least float and int support...

I've read a bit
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html
and they tend to suggest using dtype objects, if I do:
```
>>> a = np.float32(1.0)
>>> a
1.0
>>> isinstance(a, float)
False
>>> a.astype(float)
1.0
>>> isinstance(a.astype(float), float)
True
```

Would using `astype` work for your use-case then?

**Comment by HaHeho** [comment]
Thanks for the reply. You are correct, using either `.astype(np.float64)` or `.astype(float)` should always work (considering that there is no overflow or rounding errors when casting from a dtype with larger word length of course). This is due to the fact that 64 bit numpy float is equivalent to the standard Python version, see excerpt from your documentation link:
> Note that, above, we use the Python float object as a dtype. NumPy knows that int refers to np.int_, bool means np.bool_, that float is np.float_ and complex is np.complex_. The other data-types do not have Python equivalents.

But considering that this will be used simply for reporting or debugging purposes with low precision anyways, the type cast is not very pretty and possibly quite some overhead. So the question is, if this is really the recommended way to safely handle numpy data or if there might be a better alternative.

**Comment by attwad** [comment]
Well I am not sure I'd like python-osc to have to support each and every kind of custom data type  that other libraries define, to that end maybe a better solution would be to just use the OSC blob type and have numpy serialize/deserialize the data? (either using `numpy.save`, `numpy.ndarray.tobytes` or something else that I don't know) this way there is no data loss.

**Comment by HaHeho** [comment]
I think this issue can be closed. To conclude

Something like this seems recommended if one wants to report e.g. an RMS value of a signal (contained in `ndarray` or arbitrary `dtype`) as a rounded floating point:
```
osc_client.send_message('CLIENT_NAME/rms', np.round(rms, 1).astype(np.float64))
```

Alternatively, the reporting could also happen as a string, where you'd have to parse the value in the respective manner before handing it to OSC.
