### ISSUE TITLE
Add version change log

### ISSUE THREAD

**Issue by HaHeho** [attwad/python-osc#115]
I noticed that there was a version bump in the PyPI package so I gladly updated. 👍 

Anyhow, I realized that it is very difficult to see what changes have been made since a certain version. Of course this is crucial to check for potential compatibility issues. Crawling through GitHub Issues and Commit messages is not really a solution. A brief change log on GitHub and PyPI would be very appreciated!

**Comment by attwad** [comment]
Yes, thanks for the feedback, I agree a changelog would make updates nicer.
I'll add an empty changelog for now and will update it whenever the next release comes.

**Comment by HaHeho** [comment]
Excellent. Doing that, maybe you could add changes of the last couple of versions as well?! ;)

**Comment by attwad** [comment]
Added the last version, it's indeed painful to dig through commit logs... ;)
