### ISSUE TITLE
Rename package so that it complies with packaging standards

### ISSUE THREAD

**Issue by m-roberts** [attwad/python-osc#132]
When trying to package this for Debian, the [`source-package-encodes-python-version`](https://lintian.debian.org/tags/source-package-encodes-python-version) package quality check tag is triggered.

> This source package encodes a Python version in its name such as `python2-foo` or `python3-bar`.
>
> This could result in a misleading future situation where this source package supports multiple versions as well unnecessary given that the binary package names will typically encode the supported versions.

If the package were called, for example, `osc-py`, then the Debian package would be called `python3-osc-py`, and everything would play nice.

**Comment by dvzrv** [comment]
Hm, but why do you not rename it for your packaging purposes?
You are free to name the package whatever (AFAIK). I feel it's a bit much to ask upstreams to rename their project, because downstream build tooling is pedantic about naming.

**Comment by m-roberts** [comment]
You are right. I was thinking about the issue of packaging differently when I wrote this ticket - I can agree that it was a bit overzealous! I will simply add it as an overridden tag in the Debian packaging.
