### ISSUE TITLE
Missing `LICENSE` in wheel

### ISSUE THREAD

**Issue by m-roberts** [attwad/python-osc#133]
There is no `python_osc-1.7.4.dist-info/LICENSE` in the wheel on PyPI.

[This](https://stackoverflow.com/a/48691876) post seems to suggest it's as simple as adding a `setup.cfg`:
```
[metadata]
license_files = LICENSE.txt
```

**Comment by attwad** [comment]
Fixed by https://github.com/attwad/python-osc/commit/fd611354bd9351daee81d27a33b76b983ab1329f
