### ISSUE TITLE
Publish type annotations?

### ISSUE THREAD

**Issue by PeterJCLaw** [attwad/python-osc#155]
It looks like this project is type annotated, yet those annotations aren't available to consumers. In case you're not aware, you can add a [`py.typed` file](https://peps.python.org/pep-0561/#packaging-type-information) in the root of the package which will allow type checkers to use the type annotations to validate against consuming/calling code.

**Comment by attwad** [comment]
I didn't know about the py.typed file, I'll see how to incorporate this thank you for the pointer.
Note I'm currently travelling without my computer so I don't expect it to be done this summer but I'll try to get that done when I'm back, I can also gladly review pull requests :)
