### ISSUE TITLE
wildcards only work one direction

### ISSUE THREAD

**Issue by wraybowling** [attwad/python-osc#17]
A client can use wildcard to point to many dispatcher mappings
Dispatcher CANNOT use wildcard to map many addresses to a single callback

I'd like to use the latter pattern so that the client needs only to specify the name of a target, perhaps with a prefix, and the rest of the string can be parsed further manually.

**Comment by attwad** [comment]
Hi, yes that's the current behaviour. I don't think I'll have time soon to send a quick as it's a non-trivial change. If you want to contribute I welcome pull requests (with tests) :) Cheers

**Comment by wraybowling** [comment]
I'm definitely interested in looking in to what I can do to contribute. Could you describe how the mappings are stored in the Dispatcher class? Is that list accessible from the parsing functions that filter the OSC message? Where are those presently? If you were to write the feature yourself, how would you imagine it working in pseudo-code?

**Comment by attwad** [comment]
Thanks for wanting to contribute.
The mappings are stored as a simple map {} in the dispatcher (https://github.com/attwad/python-osc/blob/master/pythonosc/dispatcher.py) class.

In this map, keys are the exact endpoint (what you want to change) and is mapped to a handler with optional arguments.

the method handlers_for_address(...) takes a pattern and matches it with the exact endpoints (the keys in the map), then return the handlers that matched.

I suggest you first write a test in https://github.com/attwad/python-osc/blob/master/pythonosc/test/test_dispatcher.py which would reflect what you want, and then focus on making this test pass, most likely by modifying the handlers_for_address method.

**Comment by jsheedy** [comment]
I also wanted to map addresses with wildcards.  I created a pull request with a few tests. The test suite passes and my app works now as well :).   Please let me know what you think: https://github.com/attwad/python-osc/pull/19
