### ISSUE TITLE
Reinstate type annotations

### ISSUE THREAD

**Issue by PeterJCLaw** [attwad/python-osc#182]
In #157 we added and in #156 published type annotations for this package, however it seems that https://github.com/attwad/python-osc/commit/ee0a3ecddc701ad891e92ebc5db3ac575f30a99f removes them.

This is unfortunately breaking for consumers who are type checking expecting there to be annotations from this project.

I think the fix is to revert that commit, though it would be good to understand why the change was made/if there's a reason not to reinstate them.

**Comment by attwad** [comment]
Sorry this was a mistake, let's re-add the file

**Comment by attwad** [comment]
published change in v1.9.1

**Comment by PeterJCLaw** [comment]
@attwad thanks for the speedy response. Unfortunately I'm not sure this has quite worked -- https://github.com/attwad/python-osc/pull/183 targets `master`, while `v1.9.1` appears to have been released from `main` and thus doesn't contain the fix.

**Comment by attwad** [comment]
Rhaaa never try to do two things at once :D
I'll fix it on main now that it's the new default branch...

**Comment by PeterJCLaw** [comment]
Unfortunately I don't think that's worked either?

**Comment by PeterJCLaw** [comment]
@attwad thanks for merging #184; would it be possible to have a release which contains that fix? (I wonder also if it'd be worth yanking 1.9.1 & 1.9.2 from PyPI?)
