### ISSUE TITLE
Error in dispatcher.py when installing

### ISSUE THREAD

**Issue by tsaG1337** [attwad/python-osc#24]
Hi,

I get the following error either by installing it manual or using pip
```
File "/usr/local/lib/python3.2/dist-packages/pythonosc/dispatcher.py", line 53
    yield from handlers
             ^
SyntaxError: invalid syntax
```

**Comment by jsheedy** [comment]
python-osc requires Python 3.4, 'yield from' didn't exist in 3.2.

**Comment by attwad** [comment]
Yes, as jsheedy commented and as written in the readme.md, the library now requires 3.4+
