### ISSUE TITLE
Import errors after pip install

### ISSUE THREAD

**Issue by NumesSanguis** [attwad/python-osc#25]
I installed python-osc with: pip install python-osc   on a Ubuntu 14.04 with Python 2.7.6.

During the install I get the following error though:
    Installing collected packages: python-osc
      Running setup.py install for python-osc
          File "/usr/local/lib/python2.7/dist-packages/pythonosc/dispatcher.py", line 53
            yield from handlers
                     ^
        SyntaxError: invalid syntax

Also when trying: <from pythonosc import dispatcher> it gives the error:
      File "service/responder_no-kv.py", line 1, in <module>
        from pythonosc import dispatcher
      File "/usr/local/lib/python2.7/dist-packages/pythonosc/dispatcher.py", line 53
        yield from handlers
                 ^
    SyntaxError: invalid syntax

and <from pythonosc import osc_server> gives the error:
    Traceback (most recent call last):
      File "service/responder_no-kv.py", line 1, in <module>
        from pythonosc import osc_server as osc
      File "/usr/local/lib/python2.7/dist-packages/pythonosc/osc_server.py", line 33, in <module>
        import asyncio
    ImportError: No module named asyncio

I just wanted to try out the examples, did I do something wrong?

**Comment by NumesSanguis** [comment]
Sorry I didn't pay attention to the python version requirement.

**Comment by jsheedy** [comment]
This comes up every once in a while, would it be worth adding support for older versions of Python? There are some forks for that, but I haven't tried them. I'm responsible for bumping the requirement from 3.3 to 3.4, but it doesn't have to be that way.  I do kind of like adopting only the latest, but not every project can use 3.4.

**Comment by attwad** [comment]
I only have the cycles to maintain the latest version, if folks want to use python 2.x then it's fine but I don't want to complexify/break the code readability in order to do that so I prefer having forks maintained by other people who care about them. (plus I really do not want python 2.x to stay alive much longer, this is not helping the community move forward imo ;) )

**Comment by jsheedy** [comment]
I agree, I like the hard 3.4 requirement.

**Comment by NumesSanguis** [comment]
I wanted to use Kivy () as GUI with osc and even though Python 3 support is almost there for Kivy, it is still experimental. However I found out I could also use their version (which works also for Python 2.7) of osc and remove the Kivy dependencies: https://github.com/kivy/kivy/tree/master/kivy/lib/osc.

I agree it would also be better to use Python 3 and I would use it for my project if the dependencies I need are also compatible with 3.

**Comment by CorpusCallosum** [comment]
Hi, I'm having the same issue, what is the "python version requirement"?

**Comment by attwad** [comment]
Whatever is in the Travis file, that is 3.4 and 3.5
https://github.com/attwad/python-osc/blob/master/.travis.yml
