### ISSUE TITLE
OSC messages from a python-osc client are not picked up by ChucK server

### ISSUE THREAD

**Issue by Chiel92** [attwad/python-osc#31]
I'm trying to set up communication between [chuck][1] and python-osc. Chuck natively supports the OSC protocol. It appears that the messages we send from the python side do not arrive at the chuck side. All other combinations, i.e. python to python, chuck to chuck and chuck to python are working fine though.
I'm running python 3.4.4 on windows 7.
What could be going wrong here?

Here are the four files with the client/server implementations I'm using for testing.

### chuck_client.py:

    OscSend xmit;
    xmit.setHost("localhost", 5005);
    <<<"Sending">>>;
    xmit.startMsg("/debug");

### chuck_server.py:

    OscRecv orec;
    5005 => orec.port;
    orec.listen();
    orec.event("/debug") @=> OscEvent e;
    
    <<<"Waiting">>>;
    e => now;
    <<<"Received">>>;

### python_client.py:

    from pythonosc import osc_message_builder
    from pythonosc import udp_client
    
    client = udp_client.UDPClient('localhost', 5005)
    msg = osc_message_builder.OscMessageBuilder(address="/debug")
    msg = msg.build()
    print('Sending')
    client.send(msg)

### python_server.py:

    from pythonosc import dispatcher
    from pythonosc import osc_server
    
    dispatcher = dispatcher.Dispatcher()
    dispatcher.map("/debug", lambda _: print('Received'))
    
    print('Waiting')
    server = osc_server.ThreadingOSCUDPServer(
        ('localhost', 5005), dispatcher)
    print("Serving on {}".format(server.server_address))
    server.serve_forever()

  [1]: http://chuck.cs.princeton.edu/
  [2]: http://opensoundcontrol.org/
  [3]: https://github.com/attwad/python-osc

**Comment by Chiel92** [comment]
According to people at chuck issue tracker, this is a problem with python-osc: https://github.com/ccrma/chuck/issues/54#issuecomment-213495106

**Comment by attwad** [comment]
Interesting, if their dump utility cannot print more debug output than "Invalid message received" then perhaps can you send them a dump of the datagram packet to investigate (you can add a print statement in your python_client.py script to get it.
I'm wondering if the fact that your example just has an address and no params set to it is the cause... Perhaps they require some argument to be passed to any address? or my python osc client implementation doesn't cover this case nicely, not sure let's investigate.

**Comment by attwad** [comment]
Might be related to this change: https://github.com/attwad/python-osc/commit/b6c0de37a0509cd84bd7d50db34c07adf08f2abf, perhaps try removing it and seee if chunk server picks it up, if that's the cause then I'll have to check the osc 1.0 specs again to see who's right...

**Comment by Chiel92** [comment]
Outright commenting that line results in this error:

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pythonosc\parsing\osc_types.py", line 64, in get_string
    while dgram[start_index + offset] != 0:
IndexError: index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pythonosc\osc_message.py", line 26, in _parse_datagram
    self._address_regexp, index = osc_types.get_string(self._dgram, 0)
  File "C:\Python34\lib\site-packages\pythonosc\parsing\osc_types.py", line 81, in get_string
    raise ParseError('Could not parse datagram %s' % ie)
pythonosc.parsing.osc_types.ParseError: Could not parse datagram index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python_client.py", line 6, in <module>
    msg = msg.build()
  File "C:\Python34\lib\site-packages\pythonosc\osc_message_builder.py", line 100, in build
    return osc_message.OscMessage(dgram)
  File "C:\Python34\lib\site-packages\pythonosc\osc_message.py", line 22, in __init__
    self._parse_datagram()
  File "C:\Python34\lib\site-packages\pythonosc\osc_message.py", line 56, in _parse_datagram
    raise ParseError('Found incorrect datagram, ignoring it', pe)
pythonosc.osc_message.ParseError: ('Found incorrect datagram, ignoring it', ParseError('Could not parse datagram index out of range',))
```

I can also report that adding a single argument seems to make it work.

**Comment by attwad** [comment]
Alright, well then I checked the spec and this "," **must** be present even when no arguments are provided so I am guessing the issue is on the chuck side then.

From http://opensoundcontrol.org/spec-1_0:
"An OSC message consists of an OSC Address Pattern followed by an OSC Type Tag String followed by zero or more OSC Arguments."

**Comment by Chiel92** [comment]
I have to rectify my previous statement: I accidentally commented the wrong line, one that looked like it.
Commenting the line doesn't seem to make a difference for my example code though. I added a print statement of the datagram, making the client code look like

```python
from pythonosc import osc_message_builder
from pythonosc import udp_client

client = udp_client.UDPClient('localhost', 5005)
msg = osc_message_builder.OscMessageBuilder(address="/debug")
msg = msg.build()
print('Sending')
print(msg.dgram)
client.send(msg)
```

The output of the program is 

```
$ python34 -u python_client.py
Sending
b'/debug\x00\x00'
```

**Comment by attwad** [comment]
Okay I felt it was weird that it failed with this line commented out :)
b'/debug\x00\x00' is a valid OSC string for an address so I'm really not sure what's going on in chuck when it tries to parse it really... sorry for bouncing off but perhaps the discussion is best continued on their side with that info.

**Comment by Chiel92** [comment]
I'm probably missing something, but shouldn't `b'/debug\x00\x00'` contain a `','` somewhere, for the OSC Type Tag String?

**Comment by attwad** [comment]
if that is the dgram when the line is *not* commented out then yes it's a bug, and it's easy to add a test to check that, let me add one a bit later today to check for it

**Comment by attwad** [comment]
Yep I checked in https://github.com/attwad/python-osc/commit/638f6b909865d14816bc57b274e57d53d1c589e2 that the datagram indeed contained the "," at the end when no params were provided.

**Comment by Chiel92** [comment]
Okay, upon a closer look at the source code in my site_packages tells me that my python-osc version does not yet have the patch you pointed to. In my version, that lines looks like it a bit though, hence the confusion on my side. Darn! Should've paid more attention there. :) My apologies.

However, this means that the version on pypi still has this bug. Will there be an update soon? I'm gonna use the source directly from this repository though, I think.

**Comment by Chiel92** [comment]
> However, this means that the version on pypi still has this bug. Will there be an update soon? I'm gonna use the source directly from this repository though, I think.

Oh well, seems like you have already done that. Upgrading from pip gives me version 1.6 now.

**Comment by attwad** [comment]
Okay thanks for investigating, good to know this was fixed by upgrading!

**Comment by fs264** [comment]
Hi, I'm having the same issue. I installed it from the source (version 1.6) but getting the following error when running the simple_client.py example on my raspberry (running raspbian). Not sure how to fix it (I'm new to python). I'm trying to connect with pure data (which is tested and working)
```
Traceback (most recent call last):
  File "python-osc1.py", line 19, in <module>
    msg =  msg.build()
  File "build/bdist.linux-armv7l/egg/pythonosc/osc_message_builder.py", line 121, in build
  File "build/bdist.linux-armv7l/egg/pythonosc/osc_message.py", line 22, in __init__
  File "build/bdist.linux-armv7l/egg/pythonosc/osc_message.py", line 56, in _parse_datagram
pythonosc.osc_message.ParseError: ('Found incorrect datagram, ignoring it', ParseError('Could not parse datagram string index out of range',))


------------------
(program exited with code: 1)

```
