### ISSUE TITLE
Adding a `send_message` method to UDPClient

### ISSUE THREAD

**Issue by Nagasaki45** [attwad/python-osc#34]
This is a feature request to simplify a common use case of the package.

In few projects I found myself subclassing the UDPClient to send messages more easily:

```python
from collections import Iterable


class SimpleOSCClient(udp_client.UDPClient):
    """Simple OSC client with a `send_message` method."""

    def send_message(self, address, value):
        builder = osc_message_builder.OscMessageBuilder(address=address)
        if not isinstance(value, Iterable) or isinstance(value, (str, bytes)):
            values = [value]
        else:
            values = value
        for val in values:
            builder.add_arg(val)
        builder = builder.build()
        self.send(msg)
```

I think that this is a very usual case for an OSC client, and would like it to be implemented in the package itself. I understand the current attempt to decouple the client from the message, so adding this method to the existing UDPClient might be problematic. However, subclassing it in a new module will be equally sufficient. What do you think?

BTW, I will be happy to send a PR. Just want to understand if this is something you want and what implementation is preferable in your opinion.

**Comment by attwad** [comment]
Thank you very much for the request, I'm all for adding this in its own class!
Let's name it SimpleUDPClient though to make it clear it subclasses UDPClient :)
Also if you send a PR make sure to add tests for this new class too, thanks in advance.

**Comment by jsheedy** [comment]
Nice work, I was just working with python-osc yesterday and wanting this. 👍

**Comment by Nagasaki45** [comment]
Hi @attwad, thanks for merging! When do you think you will push it to pypi?

**Comment by attwad** [comment]
Pushed now (v1.6.1)
https://pypi.python.org/pypi/python-osc/1.6.1
