### ISSUE TITLE
Problem with SimpleUDPClient method

### ISSUE THREAD

**Issue by garcianava** [attwad/python-osc#40]
Hi there,

I downloaded your code two days ago and tried it on Python 3.5.2, Anaconda 4.2.0 (64-bit). I got the following error:

Traceback (most recent call last):
  File "simple_client.py", line 21, in <module>
    client = udp_client.SimpleUDPClient(args.ip, args.port)
AttributeError: module 'pythonosc.udp_client' has no attribute 'SimpleUDPClient'

I changed the line:
  client = udp_client.SimpleUDPClient(args.ip, args.port)
for:
  client = udp_client.UDPClient(args.ip, args.port)

and then everything worked fine.

Hope this helps.
Great code. Thank you.

**Comment by Nagasaki45** [comment]
Hi @garcianava. What version of `pythonosc` are you using?
The best way (AFAIK) is to use `pip list` to check. Note that this is a new feature that was introduced in version 1.6.1.

**Comment by garcianava** [comment]
Hi Tom,
it reads python-osc-1.6.2 on the linux installer. I will install it again using pip list.
Thank you.

**Comment by attwad** [comment]
@garcianava did you figure it out? I tentatively close this issue, please reopen if necessary.
