### ISSUE TITLE
error with python 3.6 on windows

### ISSUE THREAD

**Issue by younkhg** [attwad/python-osc#43]
in python 3.6 changelog (https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-0):
"bpo-25931: Don’t define socketserver.Forking* names on platforms such as Windows that do not support os.fork()."

due to this change,
there's an error:
osc_server.py line 136
class ForkingOSCUDPServer(socketserver.ForkingMixIn, OSCUDPServer):

with message:
AttributeError: module 'socketserver' has no attribute 'ForkingMixIn'

**Comment by attwad** [comment]
Thanks for reporting @younkhg. It seems that the commit that caused it is https://hg.python.org/cpython/rev/d772400a1211 in which they simply do not define these anymore.

I guess we should do the same then, wrap the definitions in osc_server with if hasattr(os, "fork"):
