### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by naamloos** [attwad/python-osc#45]
It might be me but I can't get python-osc to send to a broadcast address. It keeps coming back with a permission denied message. Any thoughts on how to fix this? I can post the exact message tomorrow.

Cheers!

**Comment by jsheedy** [comment]
Try setting SO_BROADCAST on the socket:

```Python
client = udp_client.UDPClient('192.168.0.255', 37337)
client._sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
```

**Comment by naamloos** [comment]
Wonderful! This did the trick. Thanks a lot.

**Comment by jsheedy** [comment]
Great! I wonder if this is something that could be an option in python-osc, or even on by default? As I read about socket.SO_BROADCAST it seemed like it's turned off by default to prevent accidental broadcasts. That seems a little restrictive to me, and caused confusion in this case.
