### ISSUE TITLE
bundle example

### ISSUE THREAD

**Issue by nylki** [attwad/python-osc#47]
Hey there,
Getting started with simple messages is straightforward because you included the client/server examples. However I am not sure how to create OSC-bundles, as there is no documentation.

It would be useful to have a similar bundle example next to the message example.

**Comment by attwad** [comment]
Hi,
All the classes are well rested and hopefully the tests themselves can be used as documentation:
https://github.com/attwad/python-osc/blob/master/pythonosc/test/test_osc_bundle_builder.py
Feel free to look at how bundled are built here and PRs are welcome if you think it wasn't clear enough or warrants being in the readme. Thanks!

**Comment by nylki** [comment]
@attwad Thx for the additional info in the readme. I haven't had time to work on the project, that involves your OSC module in the last two weeks. Will certainly also take a closer look at the tests.
