### ISSUE TITLE
Question: Detecting connection to server

### ISSUE THREAD

**Issue by crc32** [attwad/python-osc#49]
Is there a way for the server to know it has been connected to by a new device, perhaps with the device's IP? I'm looking for a way to allow a persistent server to update a newly connecting device with the current state, without having to explicitly include an "update" button on the TouchOSC form. I understand that I have to handle the ports myself, and ensure new devices comply with the convention, but that's a different issue.

**Comment by attwad** [comment]
You could look at an IP I guess, or maybe have an /register address mapped that devices should call when they talk to your server the first time? Might be a bit unreliable depending on which server you use though (I'm thinking of udp packet loss...)

**Comment by crc32** [comment]
Looks like TouchOSC can be configured to send a /ping message on a periodic basis. I can use that to update the various terminals.

**Comment by attwad** [comment]
Hope that worked out, I'll close this for now, please reopen if needed, thanks.
