### ISSUE TITLE
ValueError Raised when running example

### ISSUE THREAD

**Issue by mvienneau** [attwad/python-osc#54]
I get the message
`ValueError: Infered arg_value type is not supported`
when I try to run the example bundle code. I have tried adding an explicit arg_type, and it still tries to infer the type and raises the ValueError above.

This was done in python 3.5.2

**Comment by attwad** [comment]
This error is thrown from here
https://github.com/attwad/python-osc/blob/783b3b7e794b5a7fddd5491ab93a74bcfe449622/pythonosc/osc_message_builder.py#L109

Not sure if that's related but tests are passing for 3.5.5 (latest version on travis https://travis-ci.org/attwad/python-osc/jobs/318443918), can you upgrade to 3.5.5?

Also can you please tell exactly what "example bundle code" are you running? there's no bundle in the [examples](https://github.com/attwad/python-osc/tree/783b3b7e794b5a7fddd5491ab93a74bcfe449622/examples)
thanks!

**Comment by exsstas** [comment]
Hi! I got the same issue, when trying to send a bundle. I'm just copied "**Building bundles**" code and trying to send it using the same method as in *Simple client* example (with minor changes):
```
if __name__ == "__main__":
  ip = "127.0.0.1"
  port = 7777

  client = udp_client.SimpleUDPClient(ip, port)

  bundle = osc_bundle_builder.OscBundleBuilder(osc_bundle_builder.IMMEDIATELY)
  msg = osc_message_builder.OscMessageBuilder(address="/SYNC")
  msg.add_arg(4.0)
  # Add 4 messages in the bundle, each with more arguments.
  bundle.add_content(msg.build())
  msg.add_arg(2)
  bundle.add_content(msg.build())
  msg.add_arg("value")
  bundle.add_content(msg.build())
  msg.add_arg(b"\x01\x02\x03")
  bundle.add_content(msg.build())
  bundle = bundle.build()
  # You can now send it via a client as described in other examples.

  while True:
    client.send_message("/filter", random.random())
    client.send_message("/bundle", bundle)
    time.sleep(1)
    pass
```

And result is:

> Traceback (most recent call last):
  File "oscserver.py", line 36, in <module>
    client.send_message("/bun", bundle)
  File "C:\Anaconda\envs\TFinTD\lib\site-packages\pythonosc\udp_client.py", line 41, in send_message
    builder.add_arg(val)
  File "C:\Anaconda\envs\TFinTD\lib\site-packages\pythonosc\osc_message_builder.py", line 77, in add_arg
    arg_type = self._get_arg_type(arg_value)
  File "C:\Anaconda\envs\TFinTD\lib\site-packages\pythonosc\osc_message_builder.py", line 109, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

Should bundles be sent in some other way?
Thanks!

**Comment by attwad** [comment]
Hmm looking at your code it seems you're calling send_message() with a bundle that's already built, you should just call send() if you already have a bundle.
I could have chosen better names for these functions now that I think of it sorry about that.

**Comment by attwad** [comment]
Did that fix your issue? If so please close this please, thanks!

**Comment by mvienneau** [comment]
Yup! Thanks
