### ISSUE TITLE
Can't send 0 or 1 (also 0.0 and 1.0)

### ISSUE THREAD

**Issue by WayneKeenan** [attwad/python-osc#57]
Trying to send [0,1,2] results in [2, nil, nil] being seen on the server (SonicPi)

python-osc: v1.6.5
Python: 3.5.3 
SonicPi: 3.0.1
Pi3 Raspbian Stretch

Test case:

Python:
```python
from pythonosc import udp_client
sender = udp_client.SimpleUDPClient('127.0.0.1', 4559)
sender.send_message('/trigger/prophet', [0, 1, 2])
```

Sonic Pi:
```ruby
live_loop :foo do
  use_real_time
  a, b, c = sync "/osc/trigger/prophet"
  print(a,b,c)
end
```

Sonic Pi log:
```
{run: 9, time: 108.8493}
 └─ 2 nil nil
```

Sorry, not sure if this is python-osc or SonicPi issue.

**Comment by WayneKeenan** [comment]
It would appear not to be a Sonic Pi issue,  I have successfully sent `[0, 1, 2]` using NodeJS against the same Sonic Pi instance.

Node v4.8.2

My setup steps :
```bash
sudo apt-get install npm
npm install node-osc --save
```

Test case `client.js`:

```JavaScript
var osc = require('node-osc');

var client = new osc.Client('127.0.0.1', 4559);
client.send('/trigger/prophet', [0,1,2], function () {
  client.kill();
});
```

Sonic Pi log:

```
{run: 12, time: 52.7849}
 └─ 0 1 2
```

**Comment by WayneKeenan** [comment]
Attempting to force the datatype to `ARG_TYPE_INT` isn't an effective workaround: 

```python
builder = osc_message_builder.OscMessageBuilder(address="/trigger/prophet")
builder.add_arg(0, builder.ARG_TYPE_INT)
builder.add_arg(1, builder.ARG_TYPE_INT)
builder.add_arg(2)
msg = builder.build()
sender.send_message("/trigger/prophet", msg)
```

Sonic Pi log:
```
{run: 13, time: 365.1301}
 └─ 2 nil nil
```

**Comment by WayneKeenan** [comment]
The problem is in how `SimpleUDPClient` prepares the message.  

Using `UDPClient` and `OscMessageBuilder` works, but only when forcing the type using `builder.ARG_TYPE_INT`:

Working case:
```python
from pythonosc import udp_client
from pythonosc import osc_message_builder

sender = udp_client.UDPClient('127.0.0.1', 4559)

builder = osc_message_builder.OscMessageBuilder(address="/trigger/prophet")
builder.add_arg(0, builder.ARG_TYPE_INT)
builder.add_arg(1, builder.ARG_TYPE_INT)
builder.add_arg(2)
msg = builder.build()

sender.send(msg)
```

Sonic Pi log:

```
{run: 1, time: 28.8658}
 └─ 0 1 2
```

**Comment by dorfman2** [comment]
+1 to this issue.

I'm using [OSC Router](https://github.com/ETCLabs/OSCRouter)  from a raspberry pi running Raspian, to a desktop Mac OS X. I am not using `OscMessageBuilder`.

From the Raspberry Pi
```
client.send_message("cue/hangup", 0)
client.send_message("cue/hangup", 0.0)
client.send_message("cue/hangup", 1)
client.send_message("cue/hangup", 1.0)
```
Here's what [OSC Router](https://github.com/ETCLabs/OSCRouter) Receives
```
[ 17:57:40 ]  IN  [10.1.10.21:8000] [OSC Packet] cue/hangup, False(F)
[ 17:57:40 ]  IN  [10.1.10.21:8000] [OSC Packet] cue/hangup, False(F)
[ 17:57:40 ]  IN  [10.1.10.21:8000] [OSC Packet] cue/hangup, True(T)
[ 17:57:40 ]  IN  [10.1.10.21:8000] [OSC Packet] cue/hangup, True(T)
```

Accurate, but I would prefer to receive the integer. Not a big deal for my current project, but let me know if you need an additional tester.

**Comment by attwad** [comment]
Ah, please use version 1.6.4 as there was a recent change that broke integers indeed.
https://github.com/attwad/python-osc/pull/56/files

I'll revert the PR above and will push a new version.
