### ISSUE TITLE
Problems sending integer data 0 or 1 in messages

### ISSUE THREAD

**Issue by rbnpi** [attwad/python-osc#60]
In version 1.6.4 and previous I could use code as below  to send messages with data 0 or 1

```
sender=udp_client,SimpleUDPClient('192.168.1.128',4559)
sender.send_message('/test',1)
time.sleep(1)
sender.send_message('/test',0)
```
Now the 1 and 0 are not received but seem to be treated as booleans according to OSC_Data_Monitor which I used to inspect the output.
I have used such messages extensively in sending message data to Sonic Pi, but now I either
have to use values  say 2 and 4, or send the data as strings "1" and "0"

Obviously I can change my code to suit, but is there a way to send integers 1 and 0 which can be received as such? I'm not very experienced in using python so I may be missing something obvious.

For the moment I have reverted to version 1.6.4

**Comment by rbnpi** [comment]
I just uses sudo pip3 install python-osc and it gave me version 1.6.5
Then uninstalled and used sudo pip3 install python-osc==1.6.4  which worked OK.
Using Python 3.5.3 on a Raspberry Pi.

**Comment by attwad** [comment]
Weird, I took down 1.6.5 right after noticing that bug, hoping that nobody had downloaded it yet (it was live a few hours only...).
I'll upload a new 1.6.6 later today then and that will hopefully clear the cache of some pip installs. Sorry for the trouble

**Comment by rbnpi** [comment]
No problem. I guess it is a caching problem.. Thanks for a quick response.

**Comment by attwad** [comment]
Pushed version 1.6.6 to pypi
