### ISSUE TITLE
Parsing of empty string

### ISSUE THREAD

**Issue by adiutores** [attwad/python-osc#90]
When receiving a message that contains an empty string, the exception "OSC string cannot begin with a null byte" is raised.

The comment at the top of the parsing code says
```    According to the specifications, a string is:
    "A sequence of non-null ASCII characters followed by a null,
    followed by 0-3 additional null characters to make the total number
    of bits a multiple of 32".
```

However, companies are using empty strings. I've encountered this while getting the layout of channels on a DiGiCo S31, where an empty string is used to denote that the particular slot is not in use.

It's of course quite easy to fix this, by just removing this test, and then all works well in the DiGiCo case.

So the question is: Is an empty string resulting in an exception not unnecessarily harsh? Is there a reason why this restriction cannot be relaxed?

**Comment by adiutores** [comment]
Ok, catching the exception would be fine if you knew a priori that the packet contains a single string.

Unfortunately, in this case, a number of strings (and other types of data) are in the same packet, and as soon as this exception is raised, the entire packet is discarded. Here is some data demonstrating what I am trying to interpret: [S31 banks with empty strings](http://adiutores.net/cyan/reference/RemoteCapture.192.168.2.7.JustBanks.pcapng).

I agree that modifying the default behaviour to not be standard-compliant is not ideal.

What about providing an option that allows this behaviour, so that a user could specifically enable it when necessary?

**Comment by DrLuke** [comment]
What could work is to provide the ability of specifying a custom decoder. That way you could subclass the decoder and have it allow empty strings while the rest of the behavior is untouched.

**Comment by adiutores** [comment]
Yes, that could work. I need to override ```get_string()``` in osc_types.py.

What needs to be done to make that possible?

**Comment by DrLuke** [comment]
I took a look at it and didn't find an elegant way to solve this issue without major rewriting. What I suggest to you is to install pythonosc normally, and then apply a patch to the library yourself (use virtual environments if you didn't already).

**Comment by adiutores** [comment]
Ok, thanks for the feedback!

**Comment by gtrainavicius** [comment]
The spec does not define exactly what a sequence actually is and whether it can itself be 0 length. Based on this tidbit of the [spec](http://opensoundcontrol.org/spec-1_0):

> '*' in the OSC Address Pattern matches any sequence of zero or more characters

it seems that 0 length sequences are legal. So given the definition of OSC-string type:

> A sequence of non-null ASCII characters followed by a null, followed by 0-3 additional null characters to make the total number of bits a multiple of 32. (OSC-string examples) In this document, example OSC-strings will be written without the null characters, surrounded by double quotes.

it makes it legal to have exactly 0 non-null characters, followed by one null character to indicate string end, followed by 3 more null characters in a string to make its size aligned to 32 bits.

Some other OSC implementations permit usage of empty strings which make perfect sense to have in API design. There should be 3 allowed states for a string property - Nil would mean there's no value, "" (empty string) would mean that the value is defined, and it's empty, and "anything else" where the string value is non-empty string.

Also allowing empty strings to be used would make working with other OSC software possible that use empty strings in the API.
