### ISSUE TITLE
Different versions on pypi and github

### ISSUE THREAD

**Issue by dvzrv** [attwad/python-osc#91]
Hi!
Currently the version here on github is 1.8.0, while on pypi it is 1.7.0.
This is pretty bad for packaging. Please avoid this kind of drift in the future!

**Comment by attwad** [comment]
I have no idea how I typo'ed 1.8.0 when I released that one sorry, pypi should be the source of truth and github the moving head I don't want to have to deal with multiple release archives so I removed the tags on github.
