### ISSUE TITLE
Empty OSC string support

### ISSUE THREAD

**Issue by gtrainavicius** [attwad/python-osc#95]
Hello, as commented in the linked issue, there may have been a misinterpretation of the OSC spec. Full comment is below:

The spec does not define exactly what a sequence actually is and whether it can itself be 0 length. Based on this tidbit of the [spec](http://opensoundcontrol.org/spec-1_0):

> '*' in the OSC Address Pattern matches any sequence of zero or more characters

it seems that 0 length sequences are legal. So given the definition of OSC-string type:

> A sequence of non-null ASCII characters followed by a null, followed by 0-3 additional null characters to make the total number of bits a multiple of 32. (OSC-string examples) In this document, example OSC-strings will be written without the null characters, surrounded by double quotes.

it makes it legal to have exactly 0 non-null characters, followed by one null character to indicate string end, followed by 3 more null characters in a string to make its size aligned to 32 bits.

Some other OSC implementations permit usage of empty strings which make perfect sense to have in API design. There should be 3 allowed states for a string property - Nil would mean there's no value, "" (empty string) would mean that the value is defined, and it's empty, and "anything else" where the string value is non-empty string.

Also allowing empty strings to be used would make working with other OSC software possible that use empty strings in the API.

_Originally posted by @gtrainavicius in https://github.com/attwad/python-osc/issues/90#issuecomment-509303626_

**Comment by attwad** [comment]
Makes sense to support empty strings, thanks for the spec clarification.
Do you want to/can you send a PR for it?

**Comment by gtrainavicius** [comment]
Could it be as simple as removing the lines [70;72] here: https://github.com/attwad/python-osc/blob/master/pythonosc/parsing/osc_types.py#L70 ?

Looks like writing an empty string (`def write_string`) does not produce this exception.

Doing a proper pull request would take me a while to do due to a big context switch and still little knowledge of this nice library - most of my development is not done in Python environments, but your lib was perfect for a quick Python OSC server. :)

**Comment by attwad** [comment]
Not quite, I'll a PR ready soon.

**Comment by attwad** [comment]
Fixed by c6b180733bde35edf0b25cdc539f4516409d118a
