### ISSUE TITLE
How can i get the server to run only once, get me the one line of value from a continously sending client and not forever??

### ISSUE THREAD

**Issue by rockangator** [attwad/python-osc#96]

**Comment by attwad** [comment]
You can call `handle_request` instead of `serve_forever` on the server to achieve this.

Cf. docs: https://docs.python.org/2/library/socketserver.html

**Comment by ambuje** [comment]
I want the server to run for 10 secs and it should send only 10 values, when I put a while loop with  handle_request it gives me so many values. Is there any way to get 10 values in 10 second and when I close the streaming the values should stop coming
